# Guna H2 Database (Tak payah install, dia run dalam RAM)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Biar Spring buatkan table automatik
spring.jpa.hibernate.ddl-auto=update

# Bagi nampak database kat browser (untuk kita check)
spring.h2.console.enabled=true

spring.h2.console.settings.web-allow-others=true